language: php

php:
  - 5.6
  - 7.0
  - hhvm

before_script:
  - composer self-update
  - composer update

script:
  - mkdir -p build/logs
  - phpunit --coverage-clover=coverage.clover

after_script:
#  - php vendor/bin/coveralls -v

matrix:
  allow_failures:
    - php: hhvm